services:
  - type: web
    name: realfy-posture-detection-app
    env: python
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
  - key: PYTHON_VERSION
    value: 3.10.13
    plan: free
